#!/usr/bin/env node
// Dump the role distribution from a deployed subgraph (local graph-node or Goldsky) to files.
// Usage: node scripts/dump-roles.mjs <graphql-endpoint> [chainId]
// Writes:
//   dumps/role-distribution.<chainId>.json   (structured)
//   dumps/role-distribution.<chainId>.md     (human-readable tables)
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

const endpoint = process.argv[2] || "http://localhost:8000/subgraphs/name/royco-access-mainnet";
const chainId = process.argv[3] || "1";

// id -> name maps (generated by cast; see app/metadata/role-names.json)
let names = { roles: {}, actors: {} };
try {
  names = JSON.parse(readFileSync(join(root, "..", "metadata", "role-names.json"), "utf8"));
} catch {
  console.warn("[dump-roles] role-names.json not found; ids will be shown raw");
}
const roleName = (id) => names.roles[id] || `role_${id}`;
const actorName = (addr) => names.actors[(addr || "").toLowerCase()] || null;

const QUERY = `{
  _meta { block { number } hasIndexingErrors }
  roles(first: 1000, orderBy: id) {
    id onChainLabel adminRole guardianRole grantDelay
    members(first: 1000, where: { active: true }) { account { id } executionDelay grantedAt }
    functions(first: 1000) { id }
  }
  nativeRoles(first: 1000) {
    id vault roleHash adminRoleHash
    members(first: 1000, where: { active: true }) { account { id } }
  }
  operations(first: 200, where: { status: Scheduled }) { id caller target schedule }
}`;

const res = await fetch(endpoint, {
  method: "POST",
  headers: { "content-type": "application/json" },
  body: JSON.stringify({ query: QUERY }),
});
const body = await res.json();
if (body.errors) {
  console.error("[dump-roles] GraphQL errors:", JSON.stringify(body.errors, null, 2));
  process.exit(1);
}
const d = body.data;

const roles = d.roles
  .map((r) => ({
    id: r.id,
    name: roleName(r.id),
    onChainLabel: r.onChainLabel,
    adminRole: r.adminRole,
    adminRoleName: roleName(r.adminRole),
    guardianRole: r.guardianRole,
    guardianRoleName: roleName(r.guardianRole),
    grantDelaySeconds: Number(r.grantDelay),
    gatedFunctionCount: r.functions.length,
    holders: r.members.map((m) => ({
      address: m.account.id,
      actor: actorName(m.account.id),
      executionDelaySeconds: Number(m.executionDelay),
      grantedAt: m.grantedAt ? Number(m.grantedAt) : null,
    })),
  }))
  .filter((r) => r.holders.length > 0 || r.gatedFunctionCount > 0 || r.onChainLabel)
  .sort((a, b) => b.holders.length - a.holders.length || a.name.localeCompare(b.name));

const nativeRoles = d.nativeRoles.map((r) => ({
  vault: r.vault,
  roleHash: r.roleHash,
  adminRoleHash: r.adminRoleHash,
  holders: r.members.map((m) => ({ address: m.account.id, actor: actorName(m.account.id) })),
}));

const out = {
  chainId: Number(chainId),
  source: endpoint,
  indexedBlock: d._meta.block.number,
  hasIndexingErrors: d._meta.hasIndexingErrors,
  roleCount: roles.length,
  roles,
  nativeRoles,
  pendingOperations: d.operations,
};

mkdirSync(join(root, "dumps"), { recursive: true });
const jsonPath = join(root, "dumps", `role-distribution.${chainId}.json`);
writeFileSync(jsonPath, JSON.stringify(out, null, 2) + "\n");

// Human-readable markdown
const secs = (s) => (s === 0 ? "immediate" : s % 86400 === 0 ? `${s / 86400}d` : s % 3600 === 0 ? `${s / 3600}h` : `${s}s`);
let md = `# Role distribution — chain ${chainId}\n\n`;
md += `Source: \`${endpoint}\` · indexed block ${out.indexedBlock} · ${roles.length} roles with holders/bindings\n\n`;
md += `| Role | id | admin | guardian | grantDelay | holders | gated fns |\n|---|---|---|---|---|---|---|\n`;
for (const r of roles) {
  const holders = r.holders.map((h) => `${h.actor || h.address.slice(0, 10)}${h.executionDelaySeconds ? ` @${secs(h.executionDelaySeconds)}` : ""}`).join(", ") || "—";
  md += `| ${r.name} | ${r.id} | ${r.adminRoleName} | ${r.guardianRoleName} | ${secs(r.grantDelaySeconds)} | ${holders} | ${r.gatedFunctionCount} |\n`;
}
if (nativeRoles.length) {
  md += `\n## Native vault roles\n\n| vault | roleHash | holders |\n|---|---|---|\n`;
  for (const r of nativeRoles) {
    md += `| ${r.vault} | ${r.roleHash.slice(0, 12)}… | ${r.holders.map((h) => h.actor || h.address.slice(0, 10)).join(", ") || "—"} |\n`;
  }
}
const mdPath = join(root, "dumps", `role-distribution.${chainId}.md`);
writeFileSync(mdPath, md);

console.log(`[dump-roles] indexed block ${out.indexedBlock}, ${roles.length} roles, ${nativeRoles.length} native roles`);
console.log(`[dump-roles] wrote ${jsonPath}`);
console.log(`[dump-roles] wrote ${mdPath}`);
